# memory.py
"""
Simple in-memory conversation + emotional + preference memory layer
for the wellbeing agent.

- Lưu toàn bộ hội thoại theo session_id (student_id)
- Cung cấp cửa sổ ngắn (sliding window) cho LLM
- Lưu summary (tóm tắt) dài hạn
- Lưu trạng thái cảm xúc (emotional_state)
- Lưu user preferences (vd: cách xưng hô tiếng Việt)
"""

from __future__ import annotations

import time
import json
from dataclasses import dataclass, field, asdict
from typing import Dict, List, Optional, Literal, Any

Role = Literal["system", "user", "assistant"]


# ============================================================
# 1. Data models
# ============================================================

@dataclass
class Message:
    role: Role
    content: str
    timestamp: float = field(default_factory=time.time)


@dataclass
class EmotionalSnapshot:
    primary_emotion: Optional[str] = None
    secondary_emotion: Optional[str] = None
    stress_level: Optional[str] = None          # e.g. "low", "moderate", "high"
    risk_level: Optional[str] = None            # e.g. "none", "low", "medium", "high"
    notes: Optional[str] = None                 # free-text (e.g. "homesick", "exam overload")


@dataclass
class UserPreferences:
    # pronouns_vi: e.g. "mình-bạn", "tớ-cậu", "em-anh", ...
    pronouns_vi: Optional[str] = None


@dataclass
class ConversationState:
    session_id: str
    history: List[Message] = field(default_factory=list)
    summary: str = ""                           # running long-term summary
    emotional_state: EmotionalSnapshot = field(default_factory=EmotionalSnapshot)
    preferences: UserPreferences = field(default_factory=UserPreferences)


# ============================================================
# 2. In-memory store (can be swapped for DB later)
# ============================================================

_SESSIONS: Dict[str, ConversationState] = {}


def get_state(session_id: str) -> ConversationState:
    """Get or create a ConversationState for a given session_id."""
    if session_id not in _SESSIONS:
        _SESSIONS[session_id] = ConversationState(session_id=session_id)
    return _SESSIONS[session_id]


def append_message(session_id: str, role: Role, content: str) -> None:
    """Append a new message to the conversation history."""
    state = get_state(session_id)
    state.history.append(Message(role=role, content=content))


def set_summary(session_id: str, summary: str) -> None:
    """Update the long-term conversation summary (usually generated by LLM)."""
    state = get_state(session_id)
    state.summary = summary.strip()


def update_emotional_state(
    session_id: str,
    primary_emotion: Optional[str] = None,
    secondary_emotion: Optional[str] = None,
    stress_level: Optional[str] = None,
    risk_level: Optional[str] = None,
    notes: Optional[str] = None,
) -> None:
    """
    Update emotional snapshot based on your existing analysis
    (ví dụ bạn đã có code phân tích cảm xúc / stress / risk).
    """
    state = get_state(session_id)
    es = state.emotional_state

    if primary_emotion is not None:
        es.primary_emotion = primary_emotion
    if secondary_emotion is not None:
        es.secondary_emotion = secondary_emotion
    if stress_level is not None:
        es.stress_level = stress_level
    if risk_level is not None:
        es.risk_level = risk_level
    if notes is not None:
        es.notes = notes


def set_pronoun_preference(session_id: str, pronouns_vi: str) -> None:
    """
    Lưu cách xưng hô tiếng Việt ưa thích, ví dụ:
    - "mình-bạn"
    - "tớ-cậu"
    - "em-anh"
    """
    state = get_state(session_id)
    state.preferences.pronouns_vi = pronouns_vi.strip()


def get_pronoun_preference(session_id: str) -> Optional[str]:
    """Lấy cách xưng hô tiếng Việt đã lưu (nếu có)."""
    state = get_state(session_id)
    return state.preferences.pronouns_vi


def get_short_history(session_id: str, window_size: int = 8) -> List[Message]:
    """Return the last N messages as sliding window for local context."""
    state = get_state(session_id)
    if window_size <= 0:
        return []
    return state.history[-window_size:]


def get_emotional_state_json(session_id: str) -> str:
    """Return emotional state as JSON string for injecting into system prompt."""
    state = get_state(session_id)
    es_dict = asdict(state.emotional_state)
    # Filter out None values to keep prompt clean
    es_dict = {k: v for k, v in es_dict.items() if v is not None}
    if not es_dict:
        es_dict = {"info": "No emotional analysis available yet."}
    return json.dumps(es_dict, ensure_ascii=False)


def get_summary_or_default(session_id: str) -> str:
    """Return summary if available, else a short default text."""
    state = get_state(session_id)
    if state.summary.strip():
        return state.summary
    return "No long-term summary is available yet. Treat this as an early stage conversation."


# ============================================================
# 3. (Optional) Message builder for LLM – vẫn giữ để dùng sau
# ============================================================

def build_messages_for_model(
    session_id: str,
    user_input: str,
    base_system_prompt: str,
    language: str = "en",
    window_size: int = 8,
) -> List[Dict[str, str]]:
    """
    Build the messages[] payload for the LLM, including:
    - system prompt (đã gắn summary + emotional_state + pronoun preference)
    - short sliding window history
    - current user message

    base_system_prompt: chuỗi prompt có chứa {language},
    {conversation_summary}, {emotional_state_json}, {pronoun_preference}.
    """

    conversation_summary = get_summary_or_default(session_id)
    emotional_state_json = get_emotional_state_json(session_id)
    pronoun_preference = get_pronoun_preference(session_id) or "none"

    system_content = base_system_prompt.format(
        language=language,
        conversation_summary=conversation_summary,
        emotional_state_json=emotional_state_json,
        pronoun_preference=pronoun_preference,
    )

    messages: List[Dict[str, str]] = [
        {"role": "system", "content": system_content},
    ]

    # Add last N messages as dialogue context
    for msg in get_short_history(session_id, window_size=window_size):
        messages.append({"role": msg.role, "content": msg.content})

    # Add current user message
    messages.append({"role": "user", "content": user_input})

    return messages
